### ISSUE TITLE
Add other CDNs?

### ISSUE THREAD

**Issue by tomByrer** [tgvashworth/cdnjs#7]
Not sure if other CDNs are out of scope of this project, considering the project name?  [Sometimes Google's CDN is faster than CDNJS](http://www.baldnerd.com/make-your-site-faster-cloudflares-cdnjs-vs-google-hosted-libraries-shocking-results/) (read comments; usually Middle-East, China, Germany, etc).  Also [jsDlvr ](http://www.jsdelivr.com/) is an interesting CDN competitor.

**Comment by jackfranklin** [comment]
I wonder @phuu if this should form a new project which is an API for all of these CDNs combined. I don't think adding more should be added to this (as it's called "cdnjs") but maybe a new module which uses it would be good?

I'd not heard of jsDelivr but it looks good, and well worth including. CDNJS has ~300 and that has ~600 odd so that's a good number more to support from a Pulldown point of view.

**Comment by tgvashworth** [comment]
I totally agree – it should be other modules, named after the particular CDN (jsdelivr, googlecdn), and then make another module to pull them together.

> One Module to rule them all, One Module to find them, One Module to bring them all and in the darkness bind them.

**Comment by tomByrer** [comment]
Started early work on the jsdelivr version, but can't promise I can finish it (juggling too many things).
I did find that one must be careful of the project names of cdnjs vs jsdeliver:
cdnjs: angular.js & angular-ui (note the . & -)
cdnjs: angularjs & angularui
Happens with require & alot of other popular libs.

**Comment by tgvashworth** [comment]
Closing, because this is for another module.
